### ISSUE TITLE
Embedded browser mostly fails with external identity providers 

### ISSUE THREAD

**Issue by bgavrilMS** [Azure-Samples/active-directory-b2c-dotnet-desktop#68]
Google - fails
Facebook 

![image](https://user-images.githubusercontent.com/12273384/105067251-6c543c80-5a77-11eb-883b-c6d7815d975a.png)

We should default to the system browser.

GitHub

![image](https://user-images.githubusercontent.com/12273384/105067406-8f7eec00-5a77-11eb-9eea-4d59ec731b12.png)

**Comment by bgavrilMS** [comment]
System browser is not configurable as `http://localhost` redirect uri is not used.

**Comment by bgavrilMS** [comment]
CC @jennyf19 @jmprieur

**Comment by jennyf19** [comment]
@bgavrilMS will you do a PR?

**Comment by jmprieur** [comment]
@bgavrilMS : I cannot repro this one. The sample works for me. Which machine do you use? Do you have a specific browser?

**Comment by cljung** [comment]
I get the same errors with Chrome as default browser. Google just fails. AppleID fails the same way. Facebook eventually signs you in, but complains alot like above. A normal user would give up. 
Microsoft Windows [Version 10.0.19041.746]
Chrome Version 87.0.4280.141

**Comment by VietBuiHa** [comment]
Hi @jmprieur, 
I got the same issue with @cljung.
Google fails and shows an unsupported browser dialogue, Facebook asking a lot before I can be able to sign in.
Microsoft Windows [Version 10.0.19042.804]
Chrome Version [ 88.0.4324.150]
Edge Version [88.0.705.68]

**Comment by brunofreitas-br** [comment]
I got the same issue, there is any update on how to fix it?

**Comment by bgavrilMS** [comment]
Yes, during next release MSAL will be able to use WebView2, a modern embedded browser based on Microsoft Edge / Chromium. Sadly this requires for apps to install the runtime first, as it's not in the box (i.e. in Windows). Details here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/WebView2

I can publish a preview package if you'd like to try sooner.

**Comment by jennyf19** [comment]
@bgavrilMS this has been addressed correct? i was never able to repro the original issue.

**Comment by bgavrilMS** [comment]
Well, WebView2 has been added to the mix, see https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/WebView2 
I have not tested this scenario, hope it works better.

**Comment by nataliahering** [comment]
@bgavrilMS  @jennyf19  Hello, I also get the same problem. And I think I am running in to a blocker because of that

- if I use system browser, I need to define the redirect uri to be eg. http://localhost:8080, but not https. This has a security implication and also I need to implement a solution in which I try to open different ports in case one is reserved (which has still the risk that all ports will be reserved).

- if I use the embedded browser, the user has high chances to not be able to log in with social (or just give up because of the warnings in the UI like the one with facebook). Expecting our end user to download the webview2 is problematic.

Are there any alternatives

**Comment by jennyf19** [comment]
@nataliahering you are okay to use http in this scenario, I thought MSAL would pick the open port for you, so you don't need to do that yourself. You're right that the embedded browser is not ideal, also not accepted with Google.

@bgavrilMS can you provide more guidance here?

**Comment by nataliahering** [comment]
@jennyf19 thanks for the reply. I can use http, but I have two issues
1) in B2C you can't configure just http://localhost as a redirect uri (I think you can in AD), and then let it pick some free port for the interaction. You need to specify a port. So for a production scenario, I will need to have fallbacks with other ports, in case some are occupied by the user. So as a safety net, I will still add the embedded view case in case no port from the ones I tried worked
2) It is http, not https. So anyone sharing the computer can intercept the response and get the returned access token for example easily.

am I missing something?

**Comment by jennyf19** [comment]
@nataliahering Even if the auth code is intercepted, it's useless because of [PKCE](https://oauth.net/2/pkce/), which is an additional security layer for public clients. Which is done in the browser, Then MSAL will go to the /token endpoint on the back channel to redeem for the access token.

I thought b2c supported just http://localhost as a redirect URI now. You might have to go to the "preview" version of the portal, but this has been out for almost a year now. They have changed the portal a lot, so you might have to add a platform to be able to add the redirect URI, see below:
![image](https://user-images.githubusercontent.com/19942418/113926582-320a5980-97a1-11eb-8af5-76e890d34ec5.png)

**Comment by nataliahering** [comment]
o nice, it worked. Thanks a lot @jennyf19 , very helpful

**Comment by jennyf19** [comment]
@nataliahering awesome! Thanks for the quick reply. Is there something we could add to our docs or the portal UI itself to make this easier to figure out? (I admit I couldn't find it either last year when testing this feature from B2C).

**Comment by nataliahering** [comment]
@jennyf19 I think here https://docs.microsoft.com/en-gb/azure/active-directory-b2c/add-native-application?tabs=app-reg-ga it is pretty clear, I just somehow got confused. Btw, in the readme of this repo here https://github.com/Azure-Samples/active-directory-b2c-dotnet-desktop#step-4-register-your-native-app the " register your native app in your B2C tenant" redirects to the web app instructions instead, so I think it should be changed to redirect in the native app.

It would be also useful to add some documentation on how to configure the URI scheme in the .NET app, which will eventually used in the production scenario as the redirect uri instead of the localhost

**Comment by jennyf19** [comment]
@nataliahering that's great feedback. Do you mind opening a [new issue](https://github.com/Azure-Samples/active-directory-b2c-dotnet-desktop/issues/new) here in this repo and just copy/paste what you put above? thank you.

**Comment by nataliahering** [comment]
https://github.com/Azure-Samples/active-directory-b2c-dotnet-desktop/issues/73
https://github.com/Azure-Samples/active-directory-b2c-dotnet-desktop/issues/74 :)
